version: "3.9"
services:
  db:
    container_name: postgres
    hostname: dockerhost
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PW
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: $POSTGRES_INITDB_ARGS
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - ./database:/var/lib/postgresql/data
      #- ./database/setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_MAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PW
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - db
    volumes:
      - ./pg_admin:/var/lib/pgadmin

  load-csv:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - ./setup/superstore.csv:/usr/src/app/superstore.csv
    depends_on:
      - db
    command: sh -c '/bin/chmod +x /load_csv.sh && /load_csv.sh'

volumes:
  database:
  pg_admin:
  setup:
