dbt_football:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: docker
      password: docker
      port: 5432
      dbname: football_db
      schema: dbt_football
      threads: 1
      keepalives_idle: 0